@baseUrl = http://localhost:3000/users

### Create a user
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
  "name": "test",
  "email": "test11@gmail.com"
}


### Get all users
GET {{baseUrl}} HTTP/1.1